### ISSUE TITLE
Certificate expired

### ISSUE THREAD

**Issue by GeoffreyDijkstra** [postcode-nl/PostcodeNl_Api_Client#3]
Heads up, certificate expired of API: "SSL certificate problem: certificate has expired"

**Comment by GeoffreyDijkstra** [comment]
Seems fixed :smile:

**Comment by SjonHortensius** [comment]
This problem was caused by the [Sectigo AddTrust External CA Root Expiring May 30, 2020](https://support.sectigo.com/Com_KnowledgeDetailPage?Id=kA03l00000117LT) and should only have occurred on servers that had an outdated set of SSL certificates as a new intermediary has been available since 2015

Unfortunately, these connectivity issue between (a small number of) clients and our servers is virtually impossible to detect. We did however issue an alternative certificate for those affected, within a few hours of this intermediary expiring.

**Comment by GeoffreyDijkstra** [comment]
@SjonHortensius yes I noticed, luckily we have it implemented as optional service so if something like this happens the autocomplete just doesn't work and user has to manually enter his street + city. Thx for solving it :wink:

**Comment by SjonHortensius** [comment]
@GeoffreyDijkstra Good for you - but please don't use this issue-tracker for generic questions about our services in the future - we have other, dedicated channels for that
